<?php
return array(
    'MODULE_ALLOW_LIST'    =>    array('Home','Index','Proxy','Auth'),
    'DEFAULT_MODULE'       =>    'Index',
	'SESSION_AUTO_START' => true,
	//'TMPL_EXCEPTION_FILE' => './Public/404.html',
	//'ERROR_PAGE' =>'./Public/404.html',
	'URL_CASE_INSENSITIVE'  =>  true, 
    'URL_MODEL' => 2,
	'DB_TYPE' => 'mysql',
	'DB_HOST' => '127.0.0.1',
    'DB_NAME' => 'pangolin',
    'DB_USER' => 'root',
    'DB_PWD' => 'root',
    'DB_PORT' => 3306, 
    'DB_PREFIX' => 'pangolin_', 
    'DB_CHARSET' => 'utf8', 
    'DB_DEBUG' => false,
    'SHOW_PAGE_TRACE'=>false, 
    'SESSION_AUTO_START' => true, 
	'ANTI_MSG' => "安全信息校验失败\r\n请联系系统管理员",
	'ADMIN_USER' => 'admin666',
	'NAME' => 'zczxczxjc',
	'CARD' => '200',
	'SOFT' => '10',
	'EMAIL_USER' => '1834661238@qq.com',
	'EMAIL_PASS' => '',
	'QQ' => '1834661238',
	'FKW' => 'https://www.128faka.com/links/110699E1',
	'GROUP' => '22222222',
	'SHARE_MSG' => "欢迎使用穿山甲网络验证\r\n联系QQ1834661238",
	'MORE' => 'https://www.128faka.com/links/110699E1',
	'GIVE' => '150',
	'ENCRYPTION' => '1',
	'DISCLAIMER' => "免责声明\r\n还中考成绩昧着良心出美女\r\n这些年残酷林则徐才能\r\n免责声明\r\n还中考成绩昧着良心出美女\r\n这些年残酷林则徐才能\r\n免责声明\r\n还中考成绩昧着良心出美女\r\n这些年残酷林则徐才能\r\n免责声明\r\n还中考成绩昧着良心出美女\r\n这些年残酷林则徐才能\r\n免责声明\r\n还中考成绩昧着良心出美女\r\n这些年残酷林则徐才能\r\n免责声明\r\n还中考成绩昧着良心出美女\r\n这些年残酷林则徐才能\r\n免责声明\r\n还中考成绩昧着良心出美女\r\n这些年残酷林则徐才能免责声明\r\n还中考成绩昧着良心出美女\r\n这些年残酷林则徐才能\r\n免责声明\r\n还中考成绩昧着良心出美女\r\n这些年残酷林则徐才能\r\n免责声明\r\n还中考成绩昧着良心出美女\r\n这些年残酷林则徐才能\r\n免责声明\r\n还中考成绩昧着良心出美女\r\n这些年残酷林则徐才能",
	'START_URL' => 'http://e.hiphotos.baidu.com/image/pic/item/4610b912c8fcc3cef70d70409845d688d53f20f7.jpg',
	'NULL' => 'NULL',
);